name: Update Projects

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_projects]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Service Account Key
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > credentials.json

      - name: Run update_projects script
        run: |
          python update_projects.py

      - name: Commit and push changes
        run: |
          git config --global user.email "ryanzurrin@ryanzurrin.com"
          git config --global user.name "RyanZurrin"
          git add _data/projects.csv assets/logos/*
          git commit -m "Update projects.csv and logos"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}